/**
 * GENERATED — no editar a mano.
 * Fuente: apps/web/tokens/ (DTCG). Regenerar: pnpm tokens:build
 */

export const zedCssVars = {
  colorActionFocusRing: "--color-action-focus-ring",
  colorActionOnPrimary: "--color-action-on-primary",
  colorActionOnSecondary: "--color-action-on-secondary",
  colorActionPrimaryBg: "--color-action-primary-bg",
  colorActionPrimaryBgHover: "--color-action-primary-bg-hover",
  colorActionSecondaryBg: "--color-action-secondary-bg",
  colorBgBase: "--color-bg-base",
  colorBgCode: "--color-bg-code",
  colorBgMuted: "--color-bg-muted",
  colorBgSubtle: "--color-bg-subtle",
  colorBgSurface: "--color-bg-surface",
  colorBorderBase: "--color-border-base",
  colorBorderStrong: "--color-border-strong",
  colorBorderSubtle: "--color-border-subtle",
  colorButtonPrimaryBg: "--color-button-primary-bg",
  colorButtonPrimaryBgHover: "--color-button-primary-bg-hover",
  colorButtonPrimaryFg: "--color-button-primary-fg",
  colorButtonSecondaryBg: "--color-button-secondary-bg",
  colorButtonSecondaryBorder: "--color-button-secondary-border",
  colorButtonSecondaryFg: "--color-button-secondary-fg",
  colorCardBg: "--color-card-bg",
  colorCardBorder: "--color-card-border",
  colorCardFg: "--color-card-fg",
  colorFeedbackDangerBg: "--color-feedback-danger-bg",
  colorFeedbackDangerText: "--color-feedback-danger-text",
  colorFeedbackSuccessBg: "--color-feedback-success-bg",
  colorFeedbackSuccessText: "--color-feedback-success-text",
  colorFeedbackWarningBg: "--color-feedback-warning-bg",
  colorFeedbackWarningText: "--color-feedback-warning-text",
  colorInputBg: "--color-input-bg",
  colorInputBorder: "--color-input-border",
  colorInputFg: "--color-input-fg",
  colorInputFocus: "--color-input-focus",
  colorTextBase: "--color-text-base",
  colorTextLink: "--color-text-link",
  colorTextMuted: "--color-text-muted",
  colorTextOnCode: "--color-text-on-code",
  colorTextStrong: "--color-text-strong",
  accent: "--zed-accent",
  accentActive: "--zed-accent-active",
  accentBorder: "--zed-accent-border",
  accentHover: "--zed-accent-hover",
  accentOn: "--zed-accent-on",
  accentSoft: "--zed-accent-soft",
  authWidth: "--zed-auth-width",
  badgeDangerBorder: "--zed-badge-danger-border",
  badgeInfoBorder: "--zed-badge-info-border",
  badgeSuccessBorder: "--zed-badge-success-border",
  badgeWarningBorder: "--zed-badge-warning-border",
  bgCanvas: "--zed-bg-canvas",
  bgInverse: "--zed-bg-inverse",
  bgMuted: "--zed-bg-muted",
  bgRaised: "--zed-bg-raised",
  bgSubtle: "--zed-bg-subtle",
  borderDefault: "--zed-border-default",
  borderStrong: "--zed-border-strong",
  borderSubtle: "--zed-border-subtle",
  borderWidth: "--zed-border-width",
  bpLg: "--zed-bp-lg",
  bpMd: "--zed-bp-md",
  codeBg: "--zed-code-bg",
  codeFg: "--zed-code-fg",
  contentReadable: "--zed-content-readable",
  contentWide: "--zed-content-wide",
  controlHeight: "--zed-control-height",
  danger: "--zed-danger",
  dangerHover: "--zed-danger-hover",
  dangerOnSoft: "--zed-danger-on-soft",
  dangerSoft: "--zed-danger-soft",
  disabledOpacity: "--zed-disabled-opacity",
  drawerWidth: "--zed-drawer-width",
  easeStandard: "--zed-ease-standard",
  fgDefault: "--zed-fg-default",
  fgInverse: "--zed-fg-inverse",
  fgMuted: "--zed-fg-muted",
  fgStrong: "--zed-fg-strong",
  fgSubtle: "--zed-fg-subtle",
  filterMax: "--zed-filter-max",
  focusOffset: "--zed-focus-offset",
  focusRing: "--zed-focus-ring",
  focusWidth: "--zed-focus-width",
  fontMono: "--zed-font-mono",
  fontUi: "--zed-font-ui",
  info: "--zed-info",
  infoHover: "--zed-info-hover",
  infoOnSoft: "--zed-info-on-soft",
  infoSoft: "--zed-info-soft",
  leadingNormal: "--zed-leading-normal",
  leadingRelaxed: "--zed-leading-relaxed",
  leadingSnug: "--zed-leading-snug",
  leadingTight: "--zed-leading-tight",
  navIndicator: "--zed-nav-indicator",
  overlay: "--zed-overlay",
  proseMax: "--zed-prose-max",
  radiusLg: "--zed-radius-lg",
  radiusMd: "--zed-radius-md",
  radiusPill: "--zed-radius-pill",
  radiusSm: "--zed-radius-sm",
  radiusXl: "--zed-radius-xl",
  radiusXs: "--zed-radius-xs",
  selectionBg: "--zed-selection-bg",
  selectionFg: "--zed-selection-fg",
  shadowMd: "--zed-shadow-md",
  shadowSm: "--zed-shadow-sm",
  shadowXs: "--zed-shadow-xs",
  sidebarWidth: "--zed-sidebar-width",
  space1: "--zed-space-1",
  space10: "--zed-space-10",
  space12: "--zed-space-12",
  space16: "--zed-space-16",
  space2: "--zed-space-2",
  space20: "--zed-space-20",
  space24: "--zed-space-24",
  space3: "--zed-space-3",
  space4: "--zed-space-4",
  space5: "--zed-space-5",
  space6: "--zed-space-6",
  space8: "--zed-space-8",
  spinDuration: "--zed-spin-duration",
  statusbarHeight: "--zed-statusbar-height",
  success: "--zed-success",
  successHover: "--zed-success-hover",
  successOnSoft: "--zed-success-on-soft",
  successSoft: "--zed-success-soft",
  targetMin: "--zed-target-min",
  text2xl: "--zed-text-2xl",
  text3xl: "--zed-text-3xl",
  textBase: "--zed-text-base",
  textLg: "--zed-text-lg",
  textMd: "--zed-text-md",
  textSm: "--zed-text-sm",
  textXl: "--zed-text-xl",
  textXs: "--zed-text-xs",
  textareaMin: "--zed-textarea-min",
  topbarHeight: "--zed-topbar-height",
  transitionBase: "--zed-transition-base",
  transitionFast: "--zed-transition-fast",
  transitionSlow: "--zed-transition-slow",
  warning: "--zed-warning",
  warningHover: "--zed-warning-hover",
  warningOnSoft: "--zed-warning-on-soft",
  warningSoft: "--zed-warning-soft",
  weightBold: "--zed-weight-bold",
  weightMedium: "--zed-weight-medium",
  weightRegular: "--zed-weight-regular",
  weightSemibold: "--zed-weight-semibold",
  zDrawer: "--zed-z-drawer",
  zModal: "--zed-z-modal",
  zOverlay: "--zed-z-overlay",
  zShell: "--zed-z-shell",
  zSkip: "--zed-z-skip",
} as const;

export type ZedCssVar = (typeof zedCssVars)[keyof typeof zedCssVars];
export type ZedCssVarName = keyof typeof zedCssVars;

/** Hex generado desde OKLCH (theme-color / favicon). No es origen. */
export const themeColorHex = {
  light: "#f7faff",
  dark: "#070d18",
} as const;

/** Hex generado desde accent / accent-on (tema claro) para el favicon. */
export const faviconHex = {
  background: "#2369c6",
  foreground: "#f7faff",
} as const;
